MODEL_PATH = 'model'
SENTIMENT_LABEL_PARAMETER = [-1,0,1]
LOCATION_TAG = [
    "bãi biển",
    "núi",
    "thành phố",
    "nông thôn",
    "di tích lịch sử",
    "tôn giáo",
    "đảo",
    "công viên",
    "hang động",
    "sông, hồ",
    "thác nước",
    "cửa hàng",
    "đồ lưu niệm",
    "tham quan",
    "leo núi",
    "bơi lội",
    "lặn ngắm san hô",
    "lặn biển",
    "ẩm thực",
    "quẩy, bar, club",
    "thư giãn, spa",
    "mua sắm",
    "mạo hiểm",
    "chụp ảnh, sống ảo",
    "yên tĩnh",
    "đông người",
    "giá rẻ",
    "sang trọng",
    "phù hợp gia đình",
    "lãng mạn",
    "cảnh đẹp, nhìn toàn cảnh",
    "văn hóa",
    "di tích, bảo tàng",
    "chùa, đền, nhà thờ",
    "chợ truyền thống",
    "trải nghiệm địa phương",
    "rẻ",
    "giá ổn",
    "hải sản",
    "khu vui chơi"
]